'use strict';
// Safe public codes only. Raw remote diagnostics are never propagated.
const BRIDGE_REFUSAL_CODES = Object.freeze([
  'READ_ONLY_BRIDGE', 'PRIVATE_RESPONSE_REQUIRED', 'TRACKING_WORKFLOW_REQUIRED',
  'PROTECTED_CI_REQUIRED', 'BRIDGE_ORIGIN_MISMATCH', 'API_REQUEST_FAILED', 'API_RESULT_UNKNOWN',
  'WORKORDER_MISMATCH', 'UNOWNED_PLATFORM_CHANGE', 'PLATFORM_READBACK_MISMATCH',
  'AUTH_REQUIRED', 'API_PERMISSION_DENIED', 'AUTH_IDENTITY_MISMATCH', 'EXPIRED', 'REVOKED',
  'RESOURCE_MISMATCH', 'UNSCOPED_OPERATION', 'LOGIN_WORKFLOW_REQUIRED', 'BRIDGE_BUSY',
  'FAILED_DEPENDENCY', 'RESULT_UNKNOWN',
]);
module.exports = { BRIDGE_REFUSAL_CODES };
