'use strict';

const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { ContractError } = require('./contracts');
const { operations } = require('./platform-operations');

const lifecycle = ['check-contract', 'build-candidate', 'verify-local', 'verify-sandbox',
  'verify-staging', 'verify-metrics', 'pull-baseline', 'pull-bootstrap', 'verify-baseline',
  'create-workorder', 'post', 'readback-platform', 'publish', 'run-hook'];
const kebab = value => value.replace(/([a-z0-9])([A-Z])/g, '$1-$2').replace(/\./g, '-').toLowerCase();
function definitions() {
  return [
    ...operations.map(op => ({ name: kebab(op.id), operation: op.id,
      command: op.workflow || 'api-call', access: op.effect === 'read' ? 'read' : 'write',
      description: `${op.id}: ${op.method} ${op.path}${op.workflow ? ` → ${op.workflow} gates` : ''}` })),
    ...lifecycle.map(command => ({ name: command, command, access: ['post', 'create-workorder', 'publish'].includes(command) ? 'write' : 'read',
      description: `tracking-lifecycle ${command} with existing contract gates` })),
    ...['api-catalog', 'api-plan', 'api-call', 'site-coverage', 'site-open'].map(command => ({
      name: command, command, access: ['api-call', 'site-open'].includes(command) ? 'write' : 'read', description: `tracking-lifecycle ${command}` })),
  ];
}

function adapterSource(cliPath) {
  return `// Generated by tracking-lifecycle. Runtime stays in the installed Skill; reinstall if it moves.
import { cli, Strategy } from '@jackwener/opencli/registry';
import { CliError } from '@jackwener/opencli/errors';
import { spawn } from 'node:child_process';
import fs from 'node:fs';
const entry = ${JSON.stringify(cliPath)};
const definitions = ${JSON.stringify(definitions())};
for (const def of definitions) cli({
  site: 'tracking', name: def.name, description: def.description,
  strategy: Strategy.LOCAL, browser: false, access: def.access, defaultFormat: 'json',
  args: [
    { name: 'args-file', type: 'string', default: '', help: 'JSON array of --name=value arguments for the existing CLI; never include credentials' },
    { name: 'request', type: 'string', default: '', help: 'Catalog operation request JSON file' },
    { name: 'auth', type: 'string', default: '', help: 'project | pat | session | bridge | mcp' },
    { name: 'session', type: 'string', default: '', help: 'Explicit local browser session' },
    { name: 'profile', type: 'string', default: '', help: 'Explicit Chrome profile' },
    { name: 'private-output', type: 'string', default: '', help: 'New owner-only secret response file (local only)' },
    { name: 'tab', type: 'string', default: '', help: 'Explicit dedicated browser tab for site-open' },
    { name: 'page', type: 'string', default: '', help: 'Page ID from site-coverage' },
  ],
  columns: ['command', 'result'],
  func: async args => {
    let argv = [];
    if (args['args-file']) {
      try { argv = JSON.parse(fs.readFileSync(args['args-file'], 'utf8')); } catch { throw new CliError('INVALID_ARG', 'Unreadable argument file'); }
      if (!Array.isArray(argv) || argv.some(v => typeof v !== 'string' || !/^--[a-z-]+=/.test(v))) throw new CliError('INVALID_ARG', 'Argument file must contain --name=value strings');
    }
    for (const key of ['request', 'auth', 'session', 'profile', 'private-output', 'page', 'tab']) if (args[key]) argv.push('--' + key + '=' + args[key]);
    if (def.operation && def.command === 'api-call') argv.push('--operation=' + def.operation);
    if (argv.some(v => /^--(?:token|cookie|api-key|authorization)=/i.test(v))) throw new CliError('INVALID_AUTH', 'Use controlled environment or private credential files');
    const result = await new Promise((resolve, reject) => {
      const child = spawn(process.execPath, [entry, def.command, ...argv], { stdio: ['ignore', 'pipe', 'pipe'] });
      let output = '', error = '', size = 0;
      child.stdout.on('data', data => { size += data.length; if (size > 16 * 1024 * 1024) child.kill('SIGTERM'); else output += data; });
      child.stderr.on('data', data => { if (error.length < 4096) error += data; });
      child.once('error', () => reject(new CliError('TRACKING_EXECUTION_FAILED', 'Cannot start tracking CLI')));
      child.once('exit', code => {
        if (code !== 0) {
          let errorCode = 'TRACKING_EXECUTION_FAILED';
          try { const parsed = JSON.parse(error); if (/^[A-Z_]+$/.test(parsed.code)) errorCode = parsed.code; } catch {}
          reject(new CliError(errorCode, 'Tracking command failed; inspect contract, login, and readback before repeating writes'));
        } else if (size > 16 * 1024 * 1024) reject(new CliError('OUTPUT_LIMIT', 'Tracking output exceeds limit'));
        else { try { resolve(JSON.parse(output)); } catch { resolve({ status: 'ARTIFACT_OUTPUT', content: output }); } }
      });
    });
    return [{ command: def.name, result }];
  },
});
`;
}

function install(args = {}) {
  const root = path.resolve(args.root || path.join(os.homedir(), '.opencli'));
  const directory = path.join(root, 'clis', 'tracking');
  fs.mkdirSync(directory, { recursive: true });
  const file = path.join(directory, 'tracking.js');
  // Never overwrite someone else's adapter silently.
  const source = adapterSource(path.resolve(__dirname, '../bin/events-tdd.js'));
  if (fs.existsSync(file) && fs.readFileSync(file, 'utf8') !== source && args.replace !== 'true') {
    throw new ContractError('ADAPTER_EXISTS', 'adapter differs; review it and explicitly pass --replace=true');
  }
  fs.writeFileSync(file, source);
  return { status: 'ADAPTER_INSTALLED', file, commands: definitions().length,
    liveAcceptance: 'NOT_RUN', next: 'opencli validate tracking; opencli tracking site-coverage' };
}

module.exports = { lifecycle, kebab, definitions, adapterSource, install };
