import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import crypto from 'node:crypto';
import {perform,api,config,scrub} from '../scripts/client.mjs';
const c={base:'https://dam.example',user:'test',key:'a'.repeat(64)};
test('signature matches exact encoded params, named query and pagination',async()=>{let seen;const f=async url=>{seen=new URL(url);return new Response('[]')};await perform('search',{query:'鸟 & garden',limit:'2',offset:'3'},c,f);const q=seen.search.slice(1).split('&sign=')[0];assert.equal(seen.searchParams.get('sign'),crypto.createHash('sha256').update(c.key+q).digest('hex'));assert.equal(seen.searchParams.get('fetchrows'),'2');assert.equal(seen.searchParams.get('offset'),'3');assert.equal(seen.searchParams.get('search'),'鸟 & garden');});
test('write gate and limit validation occur before requests',async()=>{let called=false;const f=async()=>{called=true};await assert.rejects(perform('create',{type:1},c,f),{code:'ARGUMENT'});await assert.rejects(perform('search',{query:'a',limit:101},c,f),{code:'ARGUMENT'});assert.equal(called,false);});
test('HTTP, auth, false and HTML fail without response body or URL leak',async()=>{for(const [body,status,code]of [['secret sign=abc',500,'COMMAND_EXEC'],['secret',403,'AUTH_REQUIRED'],['false',200,'COMMAND_EXEC'],['{"status":"fail","data":"secret"}',200,'COMMAND_EXEC'],['<html>secret</html>',200,'COMMAND_EXEC']])await assert.rejects(api(c,'get_resource_data',{},undefined,async()=>new Response(body,{status})),e=>e.code===code&&!e.message.includes('secret'));await assert.rejects(api(c,'x',{},undefined,async()=>{throw Error('sign=secret')}),e=>!e.message.includes('secret'));});
test('multipart includes signed file_name and accepts 204; mutation readback',async()=>{const d=fs.mkdtempSync(path.join(os.tmpdir(),'rs-test-'));try{const p=path.join(d,'tiny.bin');fs.writeFileSync(p,'data');let requests=0;const result=await perform('upload',{ref:2,file:p,apply:'true'},c,async(url,o)=>{requests++;if(new URL(url).searchParams.get('function')==='upload_multipart'){assert.equal(new URL(url).searchParams.get('file_name'),'tiny.bin');assert.equal(o.method,'POST');assert.equal(await o.body.get('file').text(),'data');return new Response(null,{status:204});}return new Response('{"ref":2}');});assert.equal(requests,2);assert.equal(result.resource.ref,2);}finally{fs.rmSync(d,{recursive:true,force:true})}});
test('download refuses other origin, overwrites; streams hash and removes partial',async()=>{const d=fs.mkdtempSync(path.join(os.tmpdir(),'rs-test-'));try{const p=path.join(d,'out');let count=0;const f=async()=>++count===1?new Response(JSON.stringify(c.base+'/pages/download.php?access_key=secret')):new Response('data');const r=await perform('download',{ref:2,extension:'bin',output:p},c,f);assert.equal(r.sha256,crypto.createHash('sha256').update('data').digest('hex'));assert.equal(fs.statSync(p).mode&0o777,0o600);await assert.rejects(perform('download',{ref:2,extension:'bin',output:p},c,async()=>new Response(JSON.stringify(c.base+'/file'))),{code:'ARGUMENT'});await assert.rejects(perform('download',{ref:2,extension:'bin',output:path.join(d,'new')},c,async()=>new Response('"https://other.example/file"')),{code:'COMMAND_EXEC'});assert.equal(fs.existsSync(path.join(d,'new')),false);}finally{fs.rmSync(d,{recursive:true,force:true})}});
test('HTTP explicit exception and private key file checks',()=>{const env={RESOURCESPACE_URL:'http://127.0.0.1',RESOURCESPACE_USER:'test',RESOURCESPACE_API_KEY:'a'.repeat(64)};assert.throws(()=>config(env),{code:'ARGUMENT'});assert.equal(config({...env,RESOURCESPACE_ALLOW_HTTP:'true'}).user,'test');assert.throws(()=>config({...env,RESOURCESPACE_URL:'https://user:secret@dam.example'}),{code:'ARGUMENT'});});
test('known signed values redacted recursively',()=>{assert.deepEqual(scrub({api_key:'secret',data:['http://dam/file?access_key=secret&ref=1']}),{api_key:'[redacted]',data:['http://dam/file?access_key=[redacted]&ref=1']});});

test('failed download stream removes partial file and rejects login HTML',async()=>{const d=fs.mkdtempSync(path.join(os.tmpdir(),'rs-test-'));try{for(const html of [false,true]){const p=path.join(d,html?'html':'partial');let n=0;const f=async()=>{if(++n===1)return new Response(JSON.stringify(c.base+'/download'));if(html)return new Response('<html>Login</html>',{headers:{'content-type':'text/html'}});return new Response(new ReadableStream({start(controller){controller.enqueue(new Uint8Array([1,2]));controller.error(new Error('secret signed error'));}}));};await assert.rejects(perform('download',{ref:1,extension:'jpg',output:p},c,f),{code:'COMMAND_EXEC'});assert.equal(fs.existsSync(p),false);}}finally{fs.rmSync(d,{recursive:true,force:true})}});
test('official fail prevents collection success and skips readback',async()=>{let calls=0;await assert.rejects(perform('add-to-collection',{ref:2,collection:3,apply:'true'},c,async()=>{calls++;return new Response('{"status":"fail","data":{"message":"secret"}}')}),{code:'COMMAND_EXEC'});assert.equal(calls,1);});

test('JSON glTF original downloads remain supported',async()=>{const d=fs.mkdtempSync(path.join(os.tmpdir(),'rs-test-'));try{let count=0;const r=await perform('download',{ref:3,extension:'gltf',output:path.join(d,'model.gltf')},c,async()=>++count===1?new Response(JSON.stringify(c.base+'/model.gltf')):new Response('{"asset":{"version":"2.0"}}',{headers:{'content-type':'application/json'}}));assert.equal(r.bytes,27);assert.equal(fs.readFileSync(path.join(d,'model.gltf'),'utf8'),'{"asset":{"version":"2.0"}}');}finally{fs.rmSync(d,{recursive:true,force:true})}});
