'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const net = require('node:net');
const http = require('node:http');
const httpStatus = (url, headers) => new Promise((resolve, reject) => { const req = http.get(url, { headers }, res => { res.resume(); resolve(res.statusCode); }); req.on('error', reject); });
const WebSocket = require('ws');
const { createViewer } = require('../src/viewer');
test('noVNC viewer serves real browser client and proxies only same-origin binary VNC to loopback', async t => {
  const tcp = net.createServer(socket => { socket.write('RFB 003.008\n'); socket.on('data', data => socket.write(data)); });
  await new Promise(resolve => tcp.listen(0, '127.0.0.1', resolve));
  const viewer = await createViewer({ port: 0, vncPort: tcp.address().port });
  t.after(async () => { await viewer.close(); await new Promise(resolve => tcp.close(resolve)); });
  assert.equal(viewer.server.address().address, '127.0.0.1');
  const bootstrap = await fetch(viewer.url + 'bootstrap', { method: 'POST', headers: { Origin: new URL(viewer.url).origin }, body: JSON.stringify(viewer.capability) });
  assert.equal(bootstrap.status, 200);
  const proof = await bootstrap.clone().json();
  const protocols = ['web-view-v1', 'web-view-proof.' + proof.session + '.' + proof.proof];
  const cookie = bootstrap.headers.get('set-cookie').split(';')[0];
  assert.equal((await fetch(viewer.url, { headers: { Cookie: cookie } })).status, 200);
  assert.equal((await fetch(viewer.url + 'novnc/core/rfb.js', { headers: { Cookie: cookie } })).status, 200);
  const forwardedHost = '127.0.0.1:45678';
  assert.equal(await httpStatus(viewer.url, { Cookie: cookie, Host: forwardedHost, Origin: `http://${forwardedHost}` }), 200);
  assert.equal(await httpStatus(viewer.url, { Host: 'attacker.test:45678' }), 403);
  assert.equal(await httpStatus(viewer.url, { Cookie: cookie, Host: forwardedHost, Origin: 'http://127.0.0.1:45679' }), 403);
  const forwarded = new WebSocket(viewer.url.replace('http:', 'ws:') + 'websockify', protocols, { headers: { Cookie: cookie, Host: forwardedHost }, origin: `http://${forwardedHost}` });
  assert.equal((await new Promise((resolve, reject) => { forwarded.once('message', resolve); forwarded.once('error', reject); })).toString(), 'RFB 003.008\n');
  forwarded.terminate();
  assert.equal((await fetch(viewer.url + 'novnc/package.json', { headers: { Cookie: cookie } })).status, 404);
  assert.equal((await fetch(viewer.url, { headers: { Origin: 'https://other.test' } })).status, 403);
  const ws = new WebSocket(viewer.url.replace('http:', 'ws:') + 'websockify', protocols, { headers: { Cookie: cookie }, origin: new URL(viewer.url).origin });
  const first = await new Promise((resolve, reject) => { ws.once('message', resolve); ws.once('error', reject); });
  assert.equal(first.toString(), 'RFB 003.008\n');
  ws.terminate();
  const refused = new WebSocket(viewer.url.replace('http:', 'ws:') + 'websockify', protocols, { origin: 'https://other.test' });
  await new Promise(resolve => refused.once('error', resolve));
});
