'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const net = require('node:net');
const http = require('node:http');
const { once } = require('node:events');
const WebSocket = require('ws');
const { createViewer, launchBootstrap } = require('../src/viewer');
test('actual noVNC Display decodes JPEG under the shipped CSP and paints visible pixels',
  { skip: process.env.SAAS_VIEWER_BROWSER_FIXTURE !== '1', timeout: 15000 }, async t => {
    const { chromium } = require('../../../../observability/tracking-lifecycle/node_modules/playwright-core');
    let vncConnections = 0;
    const tcp = net.createServer(socket => { vncConnections++; socket.destroy(); });
    await new Promise(resolve => tcp.listen(0, '127.0.0.1', resolve));
    const viewer = await createViewer({ port: 0, vncPort: tcp.address().port });
    const launcher = launchBootstrap(viewer.url, viewer.capability, { open: false });
    let stolenCookie = '';
    const otherOrigin = http.createServer((req, res) => { stolenCookie = req.headers.cookie || ''; res.end('<title>other local task</title>'); });
    await new Promise(resolve => otherOrigin.listen(0, '127.0.0.1', resolve));
    let browser;
    t.after(async () => { launcher.close(); await browser?.close(); await new Promise(resolve => otherOrigin.close(resolve)); await viewer.close(); await new Promise(resolve => tcp.close(resolve)); });
    browser = await chromium.launch({ executablePath: '/usr/bin/google-chrome', headless: true, chromiumSandbox: true });
    const context = await browser.newContext();
    const page = await context.newPage();
    const requests = []; page.on('request', request => requests.push(request.url()));
    await page.addInitScript(() => { window.cspFailures = []; addEventListener('securitypolicyviolation', e => window.cspFailures.push(e.effectiveDirective)); });
    await page.goto('file://' + launcher.file);
    await page.waitForURL(viewer.url);
    assert.equal(await page.evaluate(() => document.cookie), '');
    assert.equal(await page.evaluate(() => location.hash), '');
    assert.equal((await page.context().cookies())[0].httpOnly, true);
    await page.waitForFunction(() => document.querySelector('#status').textContent.includes('断开'));
    assert.equal(vncConnections, 1);
    assert.equal(requests.some(url => url.includes(viewer.capability.token)), false);
    const otherUrl = `http://127.0.0.1:${otherOrigin.address().port}/`;
    const attackerTab = await page.context().newPage();
    await attackerTab.goto(otherUrl);
    assert.match(stolenCookie, /web_view_[a-f0-9]{32}=/);
    assert.equal(await attackerTab.evaluate(() => sessionStorage.getItem('web_view_proof')), null);
    const unauthorized = new WebSocket(viewer.url.replace('http:', 'ws:') + 'websockify', {
      origin: new URL(viewer.url).origin, headers: { Cookie: stolenCookie } });
    await once(unauthorized, 'error');
    const proof = await page.evaluate(() => sessionStorage.getItem('web_view_proof'));
    assert.match(proof, /^web-view-proof\.[a-f0-9]{32}\.[a-f0-9]{64}$/);
    const pixels = await page.evaluate(async () => {
      const { default: Display } = await import('/novnc/core/display.js');
      const source = document.createElement('canvas'); source.width = source.height = 8;
      source.getContext('2d').fillStyle = '#20c060'; source.getContext('2d').fillRect(0, 0, 8, 8);
      const bytes = Uint8Array.from(atob(source.toDataURL('image/jpeg').split(',')[1]), c => c.charCodeAt(0));
      const target = document.createElement('canvas'); document.body.append(target);
      const display = new Display(target); display.resize(8, 8);
      display.imageRect(0, 0, 8, 8, 'image/jpeg', bytes);
      await Promise.race([display.flush(), new Promise((_, reject) => setTimeout(() => reject(new Error('JPEG blocked: ' + JSON.stringify(window.cspFailures))), 1500))]); display.flip();
      return { rgb: [...target.getContext('2d').getImageData(4, 4, 1, 1).data], violations: window.cspFailures };
    });
    assert.deepEqual(pixels.violations, []);
    assert.equal(pixels.rgb[3], 255);
    assert.ok(pixels.rgb[1] > 150 && pixels.rgb[0] < 80 && pixels.rgb[2] > 60, JSON.stringify(pixels.rgb));
  });
