import {test} from 'node:test';
import assert from 'node:assert/strict';
import {runFileMetadataDryRun} from '../addx-console/file-metadata-write-core.mjs';
const row={fileId:'f1',fileTypeCode:'docs',fileName:'old',available:false,lastPublishedVersion:'V2',readyToPublishVersion:'V3',updateTime:'2026-01-01',url:'SIGNED-URL-SECRET'};
function deps(files=[]){const calls=[];return {calls,identity:async()=>({id:1,email:'fixture@example.invalid'}),request:async(path,method,body)=>{calls.push([path,body]);return path.endsWith('/type/list')?{fileTypes:[{code:'docs',name:'Documents'}]}:{files};}};}
test('submit rejects before credentials or native reads',async()=>{const d=deps();d.identity=()=>assert.fail();await assert.rejects(runFileMetadataDryRun('delete-type',{mode:'submit'},d),/disabled/);assert.deepEqual(d.calls,[]);});
test('delete existing empty type proposes exact code and deletion hash',async()=>{const d=deps();const [p]=await runFileMetadataDryRun('delete-type',{targetCode:'docs'},d);assert.deepEqual(p.payload,{code:'docs'});assert.equal(p.submissionImplemented,false);assert.equal(p.before.name,'Documents');assert.match(p.hash,/^[0-9a-f]{64}$/);assert.deepEqual(d.calls[1],['/filecenter/file/list',{fileTypeCode:'docs'}]);});
test('hidden unavailable/unpublished files block deletion, unknown targets fail',async()=>{await assert.rejects(runFileMetadataDryRun('delete-type',{targetCode:'docs'},deps([row])),/nonempty/);await assert.rejects(runFileMetadataDryRun('delete-type',{targetCode:'absent'},deps()),/target/);});
test('rename preserves status/version and omits signed urls, no release',async()=>{const d=deps([row]);const [p]=await runFileMetadataDryRun('rename',{targetCode:'docs',fileId:'f1',fileName:'next'},d);assert.deepEqual(p.payload,{fileId:'f1',fileName:'next'});assert.equal(p.before.available,false);assert.equal(p.before.readyToPublishVersion,'V3');assert.ok(!JSON.stringify(p).includes('SIGNED-URL-SECRET'));assert.equal(p.versionCAS,'NOT_SUPPORTED');assert.equal(d.calls.length,2);});
test('unknown mode/fields, partial shape, duplicate IDs and blank name fail closed',async()=>{for(const args of [{mode:'wat',targetCode:'docs'},{targetCode:'docs',available:true}])await assert.rejects(runFileMetadataDryRun('delete-type',args,deps()));await assert.rejects(runFileMetadataDryRun('rename',{targetCode:'docs',fileId:'f1',fileName:''},deps([row])));await assert.rejects(runFileMetadataDryRun('rename',{targetCode:'docs',fileId:'f1',fileName:'n'},deps([row,row])));await assert.rejects(runFileMetadataDryRun('delete-type',{targetCode:'docs'},deps([{...row,fileTypeCode:'other'}])));});
