import {test} from 'node:test';import assert from 'node:assert/strict';
import {runMinimumFirmwareDryRun} from '../addx-console/minimum-firmware-write-core.mjs';
const draft={modelNo:'PCBA-1',firmwareId:'2.3.4'};
function deps(rows=[]){const calls=[];return {calls,readDocument:async()=>draft,identity:async()=>({id:1,email:'fixture@example.invalid'}),request:async(path,method,body)=>{calls.push([path,method,body]);return path.startsWith('/factory/firmware/list')?{list:rows,total:rows.length}:[{modelNo:'PCBA-1',modelType:0}];}};}
test('default template never reads credentials or files and includes explicit user fields',async()=>{const d=deps();d.identity=d.readDocument=()=>assert.fail();const [p]=await runMinimumFirmwareDryRun({},d);assert.equal(p.status,'TEMPLATE_ONLY_NOT_A_PLAN');assert.deepEqual(Object.keys(p.createExample),['modelNo','firmwareId']);assert.equal(d.calls.length,0);});
test('create requires known PCBA and absent configuration, explicit SQL insertion defaults',async()=>{const d=deps();const [p]=await runMinimumFirmwareDryRun({action:'create','changes-file':'fixture'},d);assert.deepEqual(p.payload,draft);assert.equal(p.sqlInsertDefaults.type,'kernal');assert.equal(p.submissionImplemented,false);assert.equal(p.mode,'dry-run');await assert.rejects(runMinimumFirmwareDryRun({action:'create','changes-file':'fixture'},deps([{modelNo:'PCBA-1',firmwareId:'1.2.3'}])),/exists/);});
test('edit cannot create, exact current snapshot expected, version direction and no CAS explicit',async()=>{const d=deps([{modelNo:'PCBA-1',firmwareId:'3.0.0'}]);d.readDocument=async()=>({...draft,expectedCurrentFirmware:'3.0.0'});const [p]=await runMinimumFirmwareDryRun({action:'edit','changes-file':'fixture'},d);assert.equal(p.changeDirection,'LOWER_MINIMUM');assert.equal(p.versionCAS,'NOT_SUPPORTED');assert.deepEqual(p.payload,draft);await assert.rejects(runMinimumFirmwareDryRun({action:'edit','changes-file':'fixture'},deps()),/fields/);const missing=deps();missing.readDocument=d.readDocument;await assert.rejects(runMinimumFirmwareDryRun({action:'edit','changes-file':'fixture'},missing),/absent/);});
test('submit, unknown action, malformed userdata reject before native identity/HTTP',async()=>{for(const args of [{mode:'submit'},{action:'publish'}]){const d=deps();d.identity=d.readDocument=()=>assert.fail();await assert.rejects(runMinimumFirmwareDryRun(args,d));assert.equal(d.calls.length,0);}for(const data of [{...draft,release:true},{modelNo:'PCBA-1',firmwareId:'01.2.3'},{modelNo:'PCBA-1',firmwareId:'100.2.3'}]){const d=deps();d.readDocument=async()=>data;d.identity=()=>assert.fail();await assert.rejects(runMinimumFirmwareDryRun({action:'create','changes-file':'fixture'},d));}});
test('partial/changing/duplicate list and stale expected current fail closed',async()=>{const d=deps();d.request=async()=>({list:[],total:1});await assert.rejects(runMinimumFirmwareDryRun({action:'create','changes-file':'fixture'},d),/incomplete/);const q=deps([{modelNo:'PCBA-1',firmwareId:'1.2.3'},{modelNo:'PCBA-1',firmwareId:'1.2.3'}]);await assert.rejects(runMinimumFirmwareDryRun({action:'create','changes-file':'fixture'},q),/duplicate/);const e=deps([{modelNo:'PCBA-1',firmwareId:'1.2.3'}]);e.readDocument=async()=>({...draft,expectedCurrentFirmware:'9.9.9'});await assert.rejects(runMinimumFirmwareDryRun({action:'edit','changes-file':'fixture'},e),/changed/);});
test('native read-before-plan completes pages and refuses total drift before eligibility reads',async()=>{const catalog=Array.from({length:21},(_,i)=>({modelNo:'M'+i,firmwareId:'1.2.3'}));for(const drift of [false,true]){const d=deps();d.request=async(path,method,body)=>{d.calls.push([path,method,body]);if(path.startsWith('/factory/firmware/list')){assert.equal(method,'GET');const page=Number(new URL('https://fixture.invalid'+path).searchParams.get('pageIndex'));return {list:catalog.slice((page-1)*20,page*20),total:drift&&page===2?22:21};}assert.equal(method,'POST');assert.deepEqual(body,{modelType:0});return [{modelNo:'PCBA-1',modelType:0}];};if(drift){await assert.rejects(runMinimumFirmwareDryRun({action:'create','changes-file':'fixture'},d),/changed total/);assert.equal(d.calls.length,2);}else{const [p]=await runMinimumFirmwareDryRun({action:'create','changes-file':'fixture'},d);assert.equal(p.before,null);assert.equal(d.calls.length,3);}}});
