import {cli,Strategy} from '@jackwener/opencli/registry';
import {ArgumentError,CommandExecutionError,EmptyResultError} from '@jackwener/opencli/errors';
import {identity,request} from './native.mjs';
cli({site:'addx-console',name:'hardware-models',access:'read',description:'Read a bounded page of hardware specifications',strategy:Strategy.LOCAL,browser:false,args:[{name:'type',type:'int',help:'Exact model type: 0 PCBA or 1 whole device'},{name:'status',type:'int',help:'Exact model release status: 0 unreleased, 1 pending release, 2 pending review, 3 released'},{name:'material',type:'string',help:'Material number substring; server LIKE matching'},{name:'model',type:'string',help:'Model substring (server LIKE matching)'},{name:'page',type:'int',default:1,help:'Positive page number'},{name:'limit',type:'int',default:10,help:'Page size, 1 to 20'}],columns:['id','model','displayModel','modelType','category','releaseStatus','productId','updatedAt','total'],func:async(args)=>{
 const page=Number(args.page),size=Number(args.limit);if(!Number.isInteger(page)||page<1||!Number.isInteger(size)||size<1||size>20)throw new ArgumentError('page must be positive and limit must be 1 to 20');
 if(args.model!==undefined&&(typeof args.model!=='string'||!args.model.trim()||args.model.length>128))throw new ArgumentError('model must be a nonempty substring of at most 128 characters');
 if(args.type!==undefined&&(!Number.isSafeInteger(Number(args.type))||![0,1].includes(Number(args.type))))throw new ArgumentError('type must be 0 or 1');
 if(args.status!==undefined&&(!Number.isSafeInteger(Number(args.status))||![0,1,2,3].includes(Number(args.status))))throw new ArgumentError('status must be 0, 1, 2 or 3');
 if(args.material!==undefined&&(typeof args.material!=='string'||!args.material.trim()||args.material.length>128))throw new ArgumentError('material must be a nonempty substring of at most 128 characters');
 await identity();const d=await request('/device/model/list','POST',{createDate:'',lastModifyDate:'',releaseStatus:args.status===undefined?'':Number(args.status),manufacturerId:'',modelType:args.type===undefined?'':Number(args.type),modelNo:args.model?.trim()||'',categoryId:'',component:'',displayModelNo:'',customerCode:'',relationModel:'',param:'',materialNo:args.material?.trim()||'',pageIndex:page,pageSize:size});
 if(!d||!Array.isArray(d.list)||!Number.isSafeInteger(d.total)||d.total<0||d.list.length>size)throw new CommandExecutionError('Hardware model pagination contract changed');
 if(!d.list.length)throw new EmptyResultError('addx-console hardware-models','No visible models on this page');
 return d.list.map(x=>{if(!Number.isSafeInteger(x.id)||typeof x.modelNo!=='string'||typeof x.modelTypeName!=='string'||typeof x.releaseStatusName!=='string')throw new CommandExecutionError('Hardware model record contract changed');return{id:x.id,model:x.modelNo,displayModel:x.displayModelNo,modelType:x.modelTypeName,category:x.categoryName,releaseStatus:x.releaseStatusName,productId:x.productId,updatedAt:x.lastModifyTime,total:d.total};});
}});
